main/urls.py
from django.urls import path, include
from main.views import show_main, register, login_user, logout_user,load_books, search_books, search_books_blank, addToWishlist, bookReaded, filter_books_by_category, search_booksflutter, addToWishlistFlutter,markAsReadFlutter,show_wishlist

app_name = 'main'

urlpatterns = [
    # test
    path('', show_main, name='show_main'),
    path('loadbooks/', load_books, name='load_books'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('search-books/', search_books, name='search_books'),
    path('search-books-blank/', search_books_blank, name='search_books'),
    path('add-to-wishlist/', addToWishlist, name='add_to_wishlist'),
    path('add-to-read/', bookReaded, name='book_read'),
    path('filter-books-by-category/', filter_books_by_category, name='filter_books_by_category'),
    path('flutter/searchbooks/', search_booksflutter, name='search_booksflutter'),
    path('flutter/add-to-wishlist/', addToWishlistFlutter, name='add_to_wishlist_flutter'),
    path('flutter/add-to-read/', markAsReadFlutter, name='mark_as_read_flutter'),
    path('flutter/showwishlist/', show_wishlist, name='show_wishlist'),
]

read_page/urls.py
from django.urls import path
from read_page.views import show_read_page, show_xml, show_json, show_xml_by_id, show_json_by_id, delete_product, get_product_json, delete_product_flutter

app_name = 'read_page'

urlpatterns = [
    path('', show_read_page, name='show_read_page'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('delete/<int:id>', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('delete-flutter/<int:id>', delete_product_flutter, name='delete_product_flutter'),
]

readorama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('read_page/', include('read_page.urls')),
    path('', include('main.urls')),
    path('review/', include('review.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('landing-admin/', include('landing_admin.urls')),
    path('auth/', include('authentication.urls')),
]

read_page/models.py
from django.db import models
# from django.contrib.auth.models import User

# Create your models here.

read_page/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.shortcuts import redirect, get_object_or_404
from django.core import serializers
from wishlist.models import Wishlist 
from django.contrib.auth.decorators import login_required
import datetime

# Create your views here.

@login_required(login_url='/login')
def show_read_page(request):
    readBooks = Wishlist.objects.filter(user=request.user, flag = True)
    readBooks_count = readBooks.count()
    is_superuser = request.user.is_superuser
    context = {
        'appname': 'read_page',
        'readBooks' : readBooks,
        'readBooks_count' : readBooks_count,
        'is_superuser' : is_superuser,
        'last_login': datetime.datetime.strptime(request.COOKIES['last_login'], '%Y-%m-%d %H:%M:%S.%f'),
    }

    return render(request, 'read_page.html', context)   

@csrf_exempt
def delete_product(request, id):
    readBooks = Wishlist.objects.filter(user=request.user, flag = True)
    data = readBooks.objects.get(pk=id)
    data.delete()
    return HttpResponse(b"DELETED", status=201)

def show_xml(request):
    data = Wishlist.objects.filter(user=request.user, flag = True)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

@login_required(login_url='/login')
def show_json(request):
    data = Wishlist.objects.filter(user=request.user, flag = True)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login')
def show_xml_by_id(request, id):
    data = Wishlist.objects.filter(user=request.user, flag = True, pk = id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

@login_required(login_url='/login')
def show_json_by_id(request, id):
    data = Wishlist.objects.filter(user=request.user, flag = True, pk = id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login')
@csrf_exempt
def delete_product(request, id):
    data = get_object_or_404(Wishlist, user=request.user, flag=True, pk=id)
    data.delete()
    return HttpResponse(b"DELETED", status=201)

@login_required(login_url='/login')
def get_product_json(request):
    readBooks = Wishlist.objects.filter(user=request.user, flag = True)
    readBooks_count = readBooks.count()
    combined_data = []

    for item in readBooks:
        book = item.books
        combined_data.append({
            'book_id': book.pk,
            'book_name': book.name,
            'book_author': book.author,
            'book_num_reviews': book.num_review,
            'book_rating': book.rating,
            'book_genre': book.genre,
            'flag': item.flag,
            'readBooks_id': item.pk,
            'readBooks_count' : readBooks_count
        })

    return JsonResponse(combined_data, safe=False)

@csrf_exempt
def delete_product_flutter(request, id):
    try:
        # Get product by ID
        old_product = Wishlist.objects.get(pk=id)

        # Delete the product
        old_product.delete()

        return JsonResponse({"status": "success"}, status=200)

    except Wishlist.DoesNotExist:
        # If the product with the given ID does not exist
        return JsonResponse({"status": "error", "message": "Product not found"}, status=404)

    except Exception as e:
        # Handle other exceptions
        return JsonResponse({"status": "error", "message": str(e)}, status=500)

read_page/templates/read_page.html
{% extends "base.html" %}

{% block title %} Datatables {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <a>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Want To Add Books to
              Your Read Books?</button>
        </a>
      <div class="card">
        <div class="card-header card-header-primary card-header-icon">
          <h4 class="card-title"></h4>
        </div>
        <div class="card-body">
            <div id="product_table"></div>
        </div>
    </div>
  </div>
</div>

<div class="modal" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Read Books</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" style="text-align: center;">
          <span class="material-icons">
            done
          </span>
          <p>To add a book, simply go to the main page and hover over a book you want to add, then click on the
            button to add them to your read books! It's that simple.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

{% block javascripts %}

<script>
    async function getProducts() {
        return fetch("{% url 'read_page:get_product_json' %}").then((res) => res.json())
    }
    async function refreshProducts() {
        document.getElementById("product_table").innerHTML = ""
        const products = await getProducts()
        let htmlString =`<table id = "product_table" class="table">
                            <thead>
                                <tr>
                                    <th class="text-left">Read Books</th>
                                    <th>Write a Review</th>
                                    <th>Delete Book</th>
                                </tr>
                            </thead>`
        products.forEach((item) => {
            console.log(item)
            htmlString += `\n

            <tbody>
                <tr>
                    <td>${item.book_name}</td>
                    <td>
                        <a href="/review/add/${item.book_id}"> 
                            <button type="button" rel="tooltip" id="reviewBtn" class="btn btn-success btn-just-icon btn-sm">
                                <i class="material-icons">edit</i>
                            </button>   
                        </a>
                    </td>
                    <td>
                        <a>
                            <button type="button" rel="tooltip" id="deleteBtn" class="btn btn-danger btn-just-icon btn-sm" onclick="deleteProduct(${item.readBooks_id})">
                                <i class="material-icons">close</i>
                            </button>
                        </a>
                    </td>
                </tr>
            </tbody>`
        })
        
        htmlString += '</table>'
        if (products.length === 0) {
            htmlString += `<p>You haven't read any book</p>`;
        }
        else if (products.length === 1) {
            htmlString += `<p>You have read 1 book</p>`;
        }   
        else if (products.length > 1) {
            htmlString += `<p>You have read ${products.length} books</p>`;
        }

        document.getElementById("product_table").innerHTML = htmlString 
    }

    refreshProducts()

    function deleteProduct(id) {
        fetch("delete/" + id, {
            method: "POST"
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }
</script>

{% endblock javascripts %}