main/urls.py
from django.urls import path, include
from main.views import show_main, register, login_user, logout_user,load_books, search_books, search_books_blank, addToWishlist, bookReaded, filter_books_by_category, search_booksflutter, addToWishlistFlutter,markAsReadFlutter,show_wishlist

app_name = 'main'

urlpatterns = [
    # test
    path('', show_main, name='show_main'),
    path('loadbooks/', load_books, name='load_books'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('search-books/', search_books, name='search_books'),
    path('search-books-blank/', search_books_blank, name='search_books'),
    path('add-to-wishlist/', addToWishlist, name='add_to_wishlist'),
    path('add-to-read/', bookReaded, name='book_read'),
    path('filter-books-by-category/', filter_books_by_category, name='filter_books_by_category'),
    path('flutter/searchbooks/', search_booksflutter, name='search_booksflutter'),
    path('flutter/add-to-wishlist/', addToWishlistFlutter, name='add_to_wishlist_flutter'),
    path('flutter/add-to-read/', markAsReadFlutter, name='mark_as_read_flutter'),
    path('flutter/showwishlist/', show_wishlist, name='show_wishlist'),
]

read_page/urls.py
from django.urls import path
from read_page.views import show_read_page, show_xml, show_json, show_xml_by_id, show_json_by_id, delete_product, get_product_json, delete_product_flutter

app_name = 'read_page'

urlpatterns = [
    path('', show_read_page, name='show_read_page'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('delete/<int:id>', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('delete-flutter/<int:id>', delete_product_flutter, name='delete_product_flutter'),
]

readorama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('read_page/', include('read_page.urls')),
    path('', include('main.urls')),
    path('review/', include('review.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('landing-admin/', include('landing_admin.urls')),
    path('auth/', include('authentication.urls')),
]

review/urls.py
from django.urls import path
from review.views import show_reviews, add_reviews, delete_review, edit_review, get_review_json, get_book_id, get_review_json_flutter, delete_review_flutter, add_reviews_flutter, edit_review_flutter, load_review_id, load_books_by_id

app_name = 'review'

urlpatterns = [
    path('', show_reviews, name='review_main'),
    path('add/<int:id>', add_reviews, name='add_reviews'),
    path('delete/<int:id>', delete_review, name='delete_review'),
    path('edit-review/<int:id>', edit_review, name='edit_review'),
    path('get-review/', get_review_json, name='get_review_json'),
    path('get-book/<int:id>', get_book_id, name='get_book_id' ),
    path('get-review-flutter/<int:id>/', get_review_json_flutter, name='get_review_json_flutter' ),
    path('delete-review-flutter/<int:id>', delete_review_flutter, name='delete_review_flutter' ),
    path('add-review-flutter/<int:id>', add_reviews_flutter, name='add_review_flutter' ),
    path('edit-review-flutter/<int:id>', edit_review_flutter, name='edit_review_flutter' ), 
    path('load-review-id/<int:id>', load_review_id, name='load_review_id'), 
    path('load-books-id/<int:id>', load_books_by_id, name='load_books_id')
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, delete_wishlist, show_xml, show_json, show_xml_by_id, show_json_by_id, get_product_json, delete_product_ajax, mark_as_read, wishlistmodels

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='wishlist_main'),
    path('delete/<int:wishlist_id>/', delete_wishlist, name='delete_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path("get-product/", get_product_json, name="get_product_json"),
    path(
        "delete-product-ajax/<int:id>", delete_product_ajax, name="delete_product_ajax"
    ),
    path('mark-as-read/<int:book_id>/', mark_as_read, name='mark_as_read'),
    path('wishlistmodels/<int:id>/', wishlistmodels, name='wishlist_models'),
]

templates/base-admin.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="icon" type="image/png" href="/main/static/assets/img/favicon.png"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>
    ReadORama
  </title>
  
  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="/main/static/assets/css/material-dashboard.css?v=2.1.2" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="/main/static/assets/demo/demo.css" rel="stylesheet" />

  <!-- Specific Page CSS goes HERE  -->  
  {% block stylesheets %}
  
  {% endblock stylesheets %}

</head>

<body class="">
  <div class="{% block body_class %}{% endblock body_class %}">

    {% include 'sidebar-admin.html' %}

    <div class="main-panel">

      {% include 'navigation.html' %}  

      <!-- End Navbar -->
      <div class="content">
        <div class="content">
          <div class="container-fluid">

            {% block content %}{% endblock content %}

          </div>
        </div>
      </div>

      {% include 'footer.html' %}

    </div>
  </div>

  {% include 'scripts.html' %}

  {% include 'scripts-sidebar.html' %}

  {% block javascripts %}{% endblock javascripts %}

</body>
</html>

templates/base-auth.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="/main/static/assets/img/favicon.png" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        ReadORama
    </title>

    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
    <link rel="stylesheet" type="text/css"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link href="/main/static/assets/css/material-dashboard.css?v=2.1.2" rel="stylesheet" />

    {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="off-canvas-sidebar">

    <!-- Navbar -->
    {% include 'navigation-auth.html' %}

    <!-- End Navbar -->
    <div class="wrapper wrapper-full-page">

        {% block content %}{% endblock content %}

    </div>

    {% include 'scripts-auth.html' %}

    {% include 'scripts-sidebar.html' %}
    {% block javascripts %}{% endblock javascripts %}

</body>

</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="icon" type="image/png" href="/main/static/assets/img/favicon.png"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>
    ReadORama
  </title>
  
  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="/main/static/assets/css/material-dashboard.css?v=2.1.2" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="/main/static/assets/demo/demo.css" rel="stylesheet" />

  <!-- Specific Page CSS goes HERE  -->  
  {% block stylesheets %}
  
  {% endblock stylesheets %}

</head>

<body class="">
  <div class="{% block body_class %}{% endblock body_class %}">

    {% if is_superuser %}
      {% include 'sidebar-admin.html' %}
    {% else %}
      {% include 'sidebar.html' %}
    {% endif %}

    <div class="main-panel">

      {% include 'navigation.html' %}  

      <!-- End Navbar -->
      <div class="content">
        <div class="content">
          <div class="container-fluid">

            {% block content %}{% endblock content %}

          </div>
        </div>
      </div>

      {% include 'footer.html' %}

    </div>
  </div>

  {% include 'scripts.html' %}

  {% include 'scripts-sidebar.html' %}

  {% block javascripts %}{% endblock javascripts %}

</body>
</html>

templates/fixed-plugin.html
<div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Filters</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger active-color">
            <div class="badge-colors ml-auto mr-auto">
              <span class="badge filter badge-purple" data-color="purple"></span>
              <span class="badge filter badge-azure" data-color="azure"></span>
              <span class="badge filter badge-green" data-color="green"></span>
              <span class="badge filter badge-warning" data-color="orange"></span>
              <span class="badge filter badge-danger" data-color="danger"></span>
              <span class="badge filter badge-rose active" data-color="rose"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="header-title">Sidebar Background</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger background-color">
            <div class="ml-auto mr-auto">
              <span class="badge filter badge-black active" data-background-color="black"></span>
              <span class="badge filter badge-white" data-background-color="white"></span>
              <span class="badge filter badge-red" data-background-color="red"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger">
            <p>Sidebar Images</p>
            <label class="switch-mini ml-auto">
              <div class="togglebutton switch-sidebar-image">
                <label>
                  <input type="checkbox" checked="">
                  <span class="toggle"></span>
                </label>
              </div>
            </label>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="header-title">Images</li>
        <li class="active">
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/main/static/assets/img/sidebar-1.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/main/static/assets/img/sidebar-2.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/main/static/assets/img/sidebar-3.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/main/static/assets/img/sidebar-4.jpg" alt="">
          </a>
        </li>
      </ul>
    </div>
  </div>

templates/footer.html
<footer class="footer">
    <div class="container-fluid">
      <nav class="float-left">
        <ul>
          <li>
            <a target="_blank" rel="noopener noreferrer"
               href="http://localhost:8000">
              Group Project
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </footer>

templates/navigation-auth.html
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top text-white">
  <div class="container">
    <div class="navbar-wrapper">
      <a class="navbar-brand" href="/">Home</a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="sr-only">Toggle navigation</span>
      <span class="navbar-toggler-icon icon-bar"></span>
      <span class="navbar-toggler-icon icon-bar"></span>
      <span class="navbar-toggler-icon icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url 'main:register' %}" class="nav-link">
            <i class="material-icons">person_add</i>
            Register
          </a>
        </li>
        <li class="nav-item ">
          <a href="{% url 'main:login' %}" class="nav-link">
            <i class="material-icons">login</i>
            Login
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/navigation.html
<nav class="navbar navbar-expand-lg position-sticky navbar-transparent navbar-absolute fixed-top">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-just-icon btn-white btn-fab btn-round">
                    <i class="material-icons text_align-center visible-on-sidebar-regular">more_vert</i>
                    <i class="material-icons design_bullet-list-67 visible-on-sidebar-mini">view_list</i>
                </button>
            </div>
            <a class="navbar-brand" href="javascript:;">ReadORama</a>
        </div>
        <div class="collapse navbar-collapse justify-content-center">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <div>
                        <p>Welcome, {{ request.user.username }}</p>
                    </div>
                </li>
            </ul>
        </div>
        <div class="flex flex-col text-right">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <div>
                        <p>Last login: {{ last_login }}</p>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="{% url 'main:logout' %}">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/scripts-auth.html
  <script src="/main/static/assets/js/core/jquery.min.js"></script>
  <script src="/main/static/assets/js/core/popper.min.js"></script>
  <script src="/main/static/assets/js/core/bootstrap-material-design.min.js"></script>
  <script src="/main/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <script src="/main/static/assets/js/plugins/chartist.min.js"></script>
  <script src="/main/static/assets/js/plugins/bootstrap-notify.js"></script>
  <script src="/main/static/assets/js/material-dashboard.js?v=2.1.2" type="text/javascript"></script>
  <script src="/main/static/assets/demo/demo.js"></script>

templates/scripts-sidebar.html
<script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');

        $sidebar_img_container = $sidebar.find('.sidebar-background');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

        if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
          if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
            $('.fixed-plugin .dropdown').addClass('open');
          }

        }

        $('.fixed-plugin a').click(function(event) {
          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .active-color span').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-color', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data-color', new_color);
          }
        });

        $('.fixed-plugin .background-color .badge').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('background-color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-background-color', new_color);
          }
        });

        $('.fixed-plugin .img-holder').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).parent('li').siblings().removeClass('active');
          $(this).parent('li').addClass('active');


          var new_image = $(this).find("img").attr('src');

          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            $sidebar_img_container.fadeOut('fast', function() {
              $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
              $sidebar_img_container.fadeIn('fast');
            });
          }

          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $full_page_background.fadeOut('fast', function() {
              $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
              $full_page_background.fadeIn('fast');
            });
          }

          if ($('.switch-sidebar-image input:checked').length == 0) {
            var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
            $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
          }
        });

        $('.switch-sidebar-image input').change(function() {
          $full_page_background = $('.full-page-background');

          $input = $(this);

          if ($input.is(':checked')) {
            if ($sidebar_img_container.length != 0) {
              $sidebar_img_container.fadeIn('fast');
              $sidebar.attr('data-image', '#');
            }

            if ($full_page_background.length != 0) {
              $full_page_background.fadeIn('fast');
              $full_page.attr('data-image', '#');
            }

            background_image = true;
          } else {
            if ($sidebar_img_container.length != 0) {
              $sidebar.removeAttr('data-image');
              $sidebar_img_container.fadeOut('fast');
            }

            if ($full_page_background.length != 0) {
              $full_page.removeAttr('data-image', '#');
              $full_page_background.fadeOut('fast');
            }

            background_image = false;
          }
        });

        $('.switch-sidebar-mini input').change(function() {
          $body = $('body');

          $input = $(this);

          if (md.misc.sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            md.misc.sidebar_mini_active = false;

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

          } else {

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

            setTimeout(function() {
              $('body').addClass('sidebar-mini');

              md.misc.sidebar_mini_active = true;
            }, 300);
          }

          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);

        });
      });
    });
  </script>

templates/scripts.html
  <!--   Core JS Files   -->
  <script src="/main/static/assets/js/core/jquery.min.js"></script>
  <script src="/main/static/assets/js/core/popper.min.js"></script>
  <script src="/main/static/assets/js/core/bootstrap-material-design.min.js"></script>
  <script src="/main/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!-- Plugin for the momentJs  -->
  <script src="/main/static/assets/js/plugins/moment.min.js"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="/main/static/assets/js/plugins/sweetalert2.js"></script>
  <!-- Forms Validations Plugin -->
  <script src="/main/static/assets/js/plugins/jquery.validate.min.js"></script>
  <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="/main/static/assets/js/plugins/jquery.bootstrap-wizard.js"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="/main/static/assets/js/plugins/bootstrap-selectpicker.js"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="/main/static/assets/js/plugins/bootstrap-datetimepicker.min.js"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
  <script src="/main/static/assets/js/plugins/jquery.dataTables.min.js"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="/main/static/assets/js/plugins/bootstrap-tagsinput.js"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="/main/static/assets/js/plugins/jasny-bootstrap.min.js"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="/main/static/assets/js/plugins/fullcalendar.min.js"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="/main/static/assets/js/plugins/nouislider.min.js"></script>
  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
  <!-- Library for adding dinamically elements -->
  <script src="/main/static/assets/js/plugins/arrive.min.js"></script>
  <!-- Chartist JS -->
  <script src="/main/static/assets/js/plugins/chartist.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="/main/static/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/main/static/assets/js/material-dashboard.js?v=2.1.2" type="text/javascript"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="/main/static/assets/demo/demo.js"></script>

templates/sidebar-admin.html
<div class="sidebar" data-color="rose" data-background-color="black" data-image="/main/static/assets/img/sidebar-1.jpg">

    <div class="logo">
        <a rel="noopener noreferrer" href="{% url 'main:show_main' %}" class="simple-text logo-mini">
            RO
        </a>
        <a rel="noopener noreferrer" href="{% url 'main:show_main' %}" class="simple-text logo-normal">
            ReadORama
        </a>
    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="user-info">
                <a data-toggle="collapse" href="#collapseExample" class="username">
                    <span>
                        {{ request.user.username }}
                        <b class="caret"></b>
                    </span>
                </a>
                <div class="collapse" id="collapseExample">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:logout' %}">
                                <span class="sidebar-mini"> LO </span>
                                <span class="sidebar-normal"> Logout </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <ul class="nav">
            <li class="nav-item {% if 'index' in segment %} active {% endif %}">
                <a class="nav-link" href="{% url 'main:show_main' %}">
                    <i class="material-icons">add</i>
                    <p> List Books </p>
                </a>
            </li>
            <li class="nav-item {% if 'index' in segment %} active {% endif %}">
                <a class="nav-link" href="{% url 'wishlist:wishlist_main' %}">
                    <i class="material-icons">add</i>
                    <p> Wishlist </p>
                </a>
            </li>
            <li class="nav-item {% if 'index' in segment %} active {% endif %}">
                <a class="nav-link" href="{% url 'read_page:show_read_page' %}">
                    <i class="material-icons">add</i>
                    <p> Read Books </p>
                </a>
            </li>
            <li class="nav-item {% if 'index' in segment %} active {% endif %}">
                <a class="nav-link" href="{% url 'review:review_main' %}">
                    <i class="material-icons">add</i>
                    <p>Your Review</p>
                </a>
            </li>
            <li class="nav-item {% if 'index' in segment %} active {% endif %}">
                <a class="nav-link" href="/landing-admin">
                    <i class="material-icons">add</i>
                    <p> Admin Page </p>
                </a>
            </li>
        </ul>
    </div>
</div>

templates/sidebar.html
<div class="sidebar" data-color="rose" data-background-color="black" data-image="/main/static/assets/img/sidebar-1.jpg">

    <div class="logo">
        <a rel="noopener noreferrer" href="{% url 'main:show_main' %}" class="simple-text logo-mini">
            RO
        </a>
        <a rel="noopener noreferrer" href="{% url 'main:show_main' %}" class="simple-text logo-normal">
            ReadORama
        </a>
    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="user-info">
                <a data-toggle="collapse" href="#collapseExample" class="username">
                    <span>
                        {{ request.user.username }}
                        <b class="caret"></b>
                    </span>
                </a>
                <div class="collapse" id="collapseExample">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:logout' %}">
                                <span class="sidebar-mini"> LO </span>
                                <span class="sidebar-normal"> Logout </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <ul class="nav">
            <li class="nav-item {% if 'index' in segment %} active {% endif %}">
                <a class="nav-link" href="{% url 'wishlist:wishlist_main' %}">
                    <i class="material-icons">add</i>
                    <p> Wishlist </p>
                </a>
            </li>
            <li class="nav-item {% if 'index' in segment %} active {% endif %}">
                <a class="nav-link" href="{% url 'read_page:show_read_page' %}">
                    <i class="material-icons">add</i>
                    <p> Read Books </p>
                </a>
            </li>
            <li class="nav-item {% if 'index' in segment %} active {% endif %}">
                <a class="nav-link" href="{% url 'review:review_main' %}">
                    <i class="material-icons">add</i>
                    <p>Your Review</p>
                </a>
            </li>
        </ul>
    </div>
</div>